spring:
  application:
    name: basket-service

    data:
      mongodb:
        host: localhost
        port: 27017
        database: basket_service
      redis:
        host: localhost
        port: 6379
        password: ${DATABASE_PASSWORD}

    cache:
      redis:
        time-to-live: 60000

